import {
  CssBaseline,
  StyledEngineProvider,
  ThemeProvider,
} from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Provider } from "jotai";
import type { Metadata } from "next";
import { headers } from "next/headers";

import Lesson2Root from "components/containers/lesson2root";
// import { theme } from "components/containers/root/theme";
import { theme } from "components/containers/lesson2root/theme";
import Modal from "components/containers/modal";
import Notification from "components/containers/notification";
import Root from "components/containers/root";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = headers().get("x-pathname") || "";
  return (
    <html lang="ja">
      <body>
        <AppRouterCacheProvider options={{ key: "css" }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <StyledEngineProvider injectFirst>
              {pathname.includes("lesson2/auth") ? (
                <Provider>{children}</Provider>
              ) : pathname.includes("lesson2") ? (
                <Provider>
                  <Lesson2Root>{children}</Lesson2Root>
                </Provider>
              ) : pathname.includes("auth") ? (
                <>{children}</>
              ) : (
                <Provider>
                  {/* Main layout container */}
                  <Root>{children}</Root>
                  {/* Modal layout container */}
                  <Modal />
                  {/** Notification layout container */}
                  <Notification />
                </Provider>
              )}
            </StyledEngineProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
